### PR TITLE
Upgrade to VS2017

### PR DESCRIPTION
**Pull request by MarcelRoozekrans**
Upgrade of solution to use the new multi target project layout for VS2017 and added .netstandard 2.0.

### CODE REVIEW

**Review by rbeurskens — COMMENTED** [review]
@ https://github.com/Gezan/fastBinaryJSON/blob/ad5fda5dcf6da95164d41d26b3b736fe286a90a0/fastBinaryJSON/Reflection.cs#L286 
Even though this code is commented out, this overload of Type.GetType does not exist in .NET35. I would suggest something like:
```C#
        //if (t == null) // RaptorDB : loading runtime assemblies
        //{
        //   #if !NET35
        //    t = Type.GetType(typename, (name) => {
        //        return AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(z => z.FullName == name.FullName);
        //    }, null, true);
        //   #else
        //    var appAssemblies = AppDomain.CurrentDomain.GetAssemblies();
        //    t = appAssemblies.Select(asm => asm.GetType(typename, false)).FirstOrDefault(type => type != null);
        //   #endif
        //}
```

**Comment by rbeurskens** [comment]
And a small note: you .gitignore contains a lot of duplicate entries. Is this for a reason?

**Comment by Gezan** [comment]
@rbeurskens: The .gitignore is basically the default one generated by VS itself. If its unwanted we can remove it from the PR.

**Comment by mgholam** [comment]
The commented code is specific for  `RaptorDB` which is .net 4+ and a place holder for me for when I sync the code over there.

**Comment by rbeurskens** [comment]
Forgot to say I'm glad you migrated the code for use in the new VS2017 project structure. :)

Indeed, I compared .gitignore with the one Visual Studio generated (I added one to my local clone as well). The first part was the same, but the additional block contained entries also present in the first part. Good it is included imo. Just noticing the duplicate lines. 

I also use a fork with the code commented out as a submodule. I just thought: commented code is there so it can be uncommented in some situations, so it should also be maintained. If it will never be needed and/or is just obsolete, it should be removed entirely.

**Pull request closed without merging**
